name: Integração Continua SIX - Dev

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Repositorio
      uses: actions/checkout@v3

    - name: Insecure Docker Repository
      run: |
        echo '{ "insecure-registries": ["3.94.60.121:5000", "localhost:5000"] }' | sudo tee /etc/docker/daemon.json
        echo cat /etc/docker/daemon.json 
        sudo systemctl stop docker
        sudo systemctl start docker

    - name: Construção da imgem
      run:  docker build -t 3.94.60.121:5000/blog-six:dev .

  
    - name: Efetuar push da imagem
      if: success()
      run: docker push 3.94.60.121:5000/blog-six:dev

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        known_hosts: 'unnecessary'
    - name: Adding Known Hosts
      run: ssh-keyscan -p 22 -H 3.94.60.121 >> ~/.ssh/known_hosts


    - name: Realizar deploy
      uses: appleboy/ssh-action@master
      with:
        host: 3.94.60.121
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          docker pull 3.94.60.121:5000/blog-six:dev
          docker stack deploy -c /container/blog-six.stack.yml dev


